cookie:
  expiry_days: 30
  key: somesignaturekey
  name: randomstring123123123
credentials:
  usernames:
    acoplasticos:
      email: jsmith@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: Acoplasticos
      password: $2b$12$FmYYVxFoQsVXWQeEjPO3uuirXhrXMq5w6wjopNgQNUTOpOFX6p6y2
      role: admin
    rbriggs:
      email: rbriggs@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Rebecca Briggs
      password: $2b$12$uON60sh.2IdIk4cka2YILuRo4kQai.pU8McK/owmmJ.QawK85GrdK
      role: user
preauthorized:
  emails:
  - melsby@gmail.com
